version: '3.8'

services:

  telegram-bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: telegram-bot
    env_file:
      - ./telegram-bot/.env
    restart:
        always
    depends_on:
      - hh-auto-responder


  hh-auto-responder:
    build:
      context: ./hh-auto-responder
      dockerfile: Dockerfile
    container_name: hh-auto-responder
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://hh_postgres_db:5432/hh_bot
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - hh-bot-network
    depends_on:
      - hh_postgres_db


  hh_postgres_db:
    image: postgres:alpine
    container_name: hh_postgres_db
    environment:
      POSTGRES_DB: hh_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESQL_EFFECTIVE_CACHE_SIZE: 256MB
      POSTGRESQL_SHARED_BUFFERS: 128MB
    ports:
      - "5432:5432"
    networks:
      - hh-bot-network
    volumes:
      - postgres_data:/var/lib/postgresql/data


networks:
  hh-bot-network:
    driver: bridge


volumes:
  postgres_data:
