
spring:
  application:
    name: hh-auto-responder

  datasource:
    url: jdbc:postgresql://localhost:5432/hh_bot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8080


hh:
  client:
    id: client_id
    secret: secret
  redirect:
    uri: http://localhost:8080/oauth/callback
