
spring:
  application:
    name: hh-auto-responder

  datasource:
    url: jdbc:postgresql://localhost:5432/hh_bot
    username: ${postgres.username}
    password: ${postgres.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

telegram:
  bot:
    token: ${telegram.bot.token}


hh:
  client:
    id: ${hh.client.id}
    secret: ${hh.client.secret}
  redirect:
    uri: ${hh.redirect.uri}


server:
  port: 8080
