
spring:
  application:
    name: hh-auto-responder

  config:
    import: optional:classpath:application-secret.yml

  datasource:
    url: jdbc:postgresql://hh_postgres_db:5432/hh_bot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

telegram:
  bot:
    token: ${telegram.bot.token}


hh:
  client:
    id: ${hh.client.id}
    secret: ${hh.client.secret}
  redirect:
    uri: ${hh.redirect.uri}


server:
  port: 8080
